#Modul Customer
modul_customer="xpath://span[@class='ml-2'][normalize-space()='Customer']"
input_no_customer_jba="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik No Customer JBA']"
input_pilih_tipe_customer="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//div//div[@data-value='form-customer-type']//div"
input_pilih_membership="//div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//div//div[@data-value='form-membership-id']//div"
input_nama_depan="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik Nama Depan']"
input_nama_belakang="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik Nama Belakang']"
input_no_ponsel="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik No Ponsel']"
input_email="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik Email']"
input_tempat_lahir="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik Tempat Lahir']"
input_tanggal_lahir="xpath://div[contains(@blocker-target,'cancel-add-modal')]//div//div//div//div//div//form//div[contains(@name,'content-section-0')]//div//div//div//input[contains(@name,'birthDate')]"
input_jenis_kelamin="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//div//div[@data-value='form-gender']//div"
input_nama_kota="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik Kota']"
input_alamat="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik Alamat']"
input_no_ktp="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik No KTP']"
input_no_npwp="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//input[@placeholder='Ketik No NPWP']"
upload_ktp="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//div//div[@name='file-uploader-ktp-url']//div[contains(text(),'File Upload')]"
upload_npwp="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//div//div//div//div[@name='file-uploader-npwp-url']//label//img"
button_selanjutnya="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-0']//div//button[@type='button'][normalize-space()='Selanjutnya']"
button_selanjutnya2="xpath://div[@class='milestone-form']//div[@class='flex mt-auto']//button[@type='button'][normalize-space()='Selanjutnya']"
input_nama_bank="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-1']//div//div//div//input[@placeholder='Ketik Nama Bank']"
input_cabang_bank="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-1']//div//div//div//input[@placeholder='Ketik Cabang Bank']"
input_no_rekening="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-1']//div//div//div//input[@placeholder='Ketik Nomor Rekening']"
upload_foto_buku_tabungan="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-1']//div//div//div//div//label//img"
input_catatan="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-1']//div//div//div//textarea[@placeholder='Ketik Catatan']"
input_tujuan_beli="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//div//div[@data-value='form-buy-purpose']//div"
input_sumber_dana="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//div//div[@data-value='form-source-of-funds']//div"
input_transaksi_untuk="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//input[@placeholder='Ketik Transaksi Untuk']"
input_jenis_kendaraan="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//div//div[@data-value='form-vehicle-type']//div"
input_other1="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//input[@placeholder='Ketik Other 1']"
input_other2="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//input[@placeholder='Ketik Other 2']"
input_other3="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//input[@placeholder='Ketik Other 3']"
input_other4="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//input[@placeholder='Ketik Other 4']"
input_other5="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//form//div[@name='content-section-2']//div//div//div//input[@placeholder='Ketik Other 5']"
status_on_customer="xpath://div[@class='milestone-form']//span[@class='switch-ex w-4 h-4 left-1.5-min absolute rounded-full transform transition-transform bg-slider-off']"
button_ya_simpan="xpath://div[@id='confirm-save-customer-modal']//button[@class='real-submit-form close-modal btn-active py-4 px-5 rounded-3xl text-sm mx-2 w-32 flex justify-center items-center'][normalize-space()='Ya, Simpan']"
button_cek_lagi="xpath://div[@id='confirm-save-customer-modal']//button[contains(@class,'recheck-button close-modal btn-grey py-4 px-5 rounded-3xl text-sm mx-2 w-32 flex justify-center items-center')][normalize-space()='Cek Lagi']"
aksi_customer="xpath://tbody/tr[1]/td[9]/div[1]/div[1]/div[1]//*[name()='svg']"
icon_export="xpath://button[@target='export-form']//*[name()='svg']"
dropdown_pilih_format="xpath://div[@data-value='form-format']//div[@class='absolute left-0 top-0 h-12 max-h-[48px] w-full searchable-cover form-input-ex']"
button_export="xpath://button[normalize-space()='Ekspor']"
icon_download="xpath://button[@target='import-form']//*[name()='svg']"
download_csv="xpath://button[normalize-space()='Download format template CSV']"
icon_resend_password="xpath://button[@class='send-password-btn modal-button btn-grey p-3 rounded-full w-12 h-12 ml-3 flex justify-center items-center cursor-pointer hover:text-success']//*[name()='svg']"
ya_mengerti_resend="xpath://button[@class='close-modal btn-active py-4 px-5 rounded-3xl text-sm']"
button_view_customer="xpath://tbody/tr[1]/td[9]/div[1]/button[1]//*[name()='svg']"