#Modul Group
modul_group= "xpath://span[normalize-space()='Group']"
input_kode_group=  "xpath://div[@blocker-target='cancel-add-modal']//div//div//div//input[@placeholder='Ketik Kode Group']"
input_nama_group=  "xpath://div[@id='add-form-modal']//input[contains(@placeholder,'Ketik Nama Group')]"
button_tambah="xpath://div[@blocker-target='cancel-add-modal']//div//div//div//div//div//div//div//div//button[@target='customer-search']"
input_cari_customer="xpath://input[@name='customerSearch' and @placeholder='Cari customer disini']"
checkbox1="xpath://body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/input[1]"
checkbox2="xpath://body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/input[1]"
checkbox3="xpath://body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/input[1]"
button_tambahkan="xpath://button[normalize-space()='Tambahkan']"
aksi_group=  "xpath://div[@class='dropdown-button flex justify-center items-center px-2.5']//*[name()='svg']"
edit_existing="xpath://span[normalize-space()='Edit']"
tambah_existing="xpath://div[@blocker-target='cancel-edit-modal']//div//div//div//div//div//div//div//div//button[@target='customer-search']"
delete_list_customer="xpath://button[@class='remove-customer-btn btn-grey-2']"
YaHapus_group="xpath://div[@class='delete-modal-confirmation']//div[1]//div[4]//button[1]"
edit_group="xpath://div[@id='dropdown-menu-0']//button[@class='w-full edit-btn modal-button']//div[@class='flex justify-start items-center']"
edit_kode_group="xpath://div[@blocker-target='cancel-edit-modal']//div//div//div//input[@name='code']"
edit_nama_group="xpath://div[@blocker-target='cancel-edit-modal']//div//div//div//input[@name='name']"
input_filter_kode_group="id:filter-code-value"
input_filter_nama_group="id:filter-name-value"
