#Locator Global
button_create="xpath://button[@class='btn-active py-3 px-4 rounded-3xl flex items-center justify-center text-xs modal-button create-button']"
button_delete="xpath://div[@id='dropdown-menu-0']//div[contains(text(),'Delete')]"
Ya_hapus="xpath://button[normalize-space()='Ya, Hapus']"
simpan=  "xpath://button[normalize-space()='Simpan']"
Ya_Mengerti_Create= "xpath://div[@id='success-modal']//a[@class='btn-active py-4 px-5 rounded-3xl text-sm'][normalize-space()='Ya, Mengerti']"
input_search=  "xpath://input[@id='searchTable']"
button_edit=  "xpath://button[@class='h-full w-full edit-btn modal-button hover:text-active flex justify-center items-center']"
update=  "xpath://button[normalize-space()='Update']"
Ya_Mengerti_Update=  "xpath://div[@id='success-update-modal']//a[@class='btn-active py-4 px-5 rounded-3xl text-sm'][normalize-space()='Ya, Mengerti']"
Ya_Mengerti_Delete=  "xpath://div[@id='success-delete-modal']//a[@class='btn-active py-4 px-5 rounded-3xl text-sm'][normalize-space()='Ya, Mengerti']"
button_filter= "xpath://span[normalize-space()='Filter']"
button_tampilkan= "xpath://span[normalize-space()='Tampilkan']"
dropdown_status="xpath://div[@class='absolute left-0 top-0 h-12 max-h-[48px] w-full searchable-cover form-input-ex-fit']"
semua_status_aktif="xpath://div[contains(text(),'Semua Status Aktif')]"
status_aktif="xpath://div[@class='w-full'][normalize-space()='Aktif']"
status_non_aktif="xpath://div[contains(text(),'Non Aktif')]"
Ya_aktifkan= "xpath://button[normalize-space()='Ya, Aktifkan']"
Ya_nonaktifkan= "xpath://button[@class='close-modal btn-active py-4 px-5 rounded-3xl text-sm mx-2 w-36 flex justify-center items-center' and (text()='Ya, Nonaktifkan')]"
status_on="xpath://span[@id='on-0' and @class='absolute font-medium text-2xs uppercase left-2 text-white']"
status_off="xpath://span[@id='off-0' and @class='absolute font-medium text-2xs uppercase right-2 text-toggle-off']"
dropdown_size_table="xpath://div[@class='dropdown-button btn-grey-2 text-gray-500 flex justify-center items-center rounded-3xl px-3 py-5']"
tabel_10="xpath://td[normalize-space()='10']"
tabel_20="xpath://td[normalize-space()='20']"
tabel_50="xpath://td[normalize-space()='50']"
tabel_100="xpath://td[normalize-space()='100']"
page2="xpath://button[normalize-space()='2']"
Ya_Mengerti_Delete_GroupEx="xpath://div[@id='success-delete-customer-from-group-modal']//div[contains(@class,'flex justify-center')]"