#Modul Merek
modul_Merek_Model_Type=  "xpath://span[normalize-space()='Merek/Model/Tipe']"
tab_model= "xpath://a[normalize-space()='Model']"
tab_tipe=  "xpath://a[normalize-space()='Tipe']"
tab_merek=  "xpath://a[normalize-space()='Merek']"
input_search=  "xpath://input[@id='searchTable']"
status_on=  "xpath://input[@id='toggle-0']"
edit=  "xpath://button[@target='edit-form']"
button_filter= "xpath://button[@class='filter-table-button btn-grey py-3 px-4 rounded-3xl flex items-center justify-center text-xs']"
input_nama_merek="xpath://div[@id='add-form-modal']//input[@name='name']"
button_tampilkan="xpath://button[@class='submit-filter btn-active ml-auto p-3 rounded-3xl flex items-center justify-center text-xs w-24 h-12']"
aksi_merek= "xpath://tbody/tr[1]/td[5]/div[1]/div[1]/div[1]//*[name()='svg']"
delete_merek_model_type="xpath://div[@id='dropdown-menu-0']//div[contains(text(),'Delete')]"
Ya_hapus_merek_model_type="xpath://div//button[normalize-space()='Ya, Hapus']"
dropdown_objek_filter="xpath://div[@data-value='form-filter-object-category-id']//div[@class='absolute left-0 top-0 h-12 max-h-[48px] w-full searchable-cover form-input-ex-fit']"
filter_bike="xpath://div[@class='flex items-center p-3 hover:bg-gray-200 dropdown-item dropdown-item-form-filter-object-category-id']//div[@class='w-full'][normalize-space()='Bike']"
semua_objek_lelang="xpath://div[contains(text(),'Semua Objek Lelang')]"
filter_car="xpath://div[@class='flex items-center p-3 hover:bg-gray-200 dropdown-item dropdown-item-form-filter-object-category-id']//div[@class='w-full'][normalize-space()='Car']"
input_nama_merek_edit="xpath://div[@id='edit-form-modal']//input[@name='name']"
#Modul Model
button_create_model="xpath://button[@class='btn-active py-3 px-4 rounded-3xl flex items-center justify-center text-xs modal-button create-button']"
pilih_merek="xpath://div[@id='selectable-input-brand']//div[@class='dropdown-button-ex relative']//div[@class='absolute left-0 top-0 h-12 max-h-[48px] w-full searchable-cover form-input-ex']"
input_nama_model="xpath://div[@id='add-form-modal']//input[@class='form-input mb-1 h-12 max-h-[48px]']"
input_edit_nama_model="xpath://div[@id='edit-form-modal']//input[@name='name']"
aksi_model="xpath://tbody/tr[1]/td[6]/div[1]/div[1]/div[1]//*[name()='svg']"
#Modul Type
aksi_type="xpath://tbody/tr[1]/td[7]/div[1]/div[1]/div[1]//*[name()='svg']"
pilih_model="xpath://div[@id='selectable-input-model'] //div[@class='dropdown-button-ex relative']//div[@class='absolute left-0 top-0 h-12 max-h-[48px] w-full searchable-cover form-input-ex']"
input_tipe="xpath://div[@id='add-form-modal']//input[@placeholder='Ketik Nama Tipe']"
input_tipe_edit="xpath://div[@id='edit-form-modal']//input[@name='name']"