#Modul Cabang
modul_cabang= "xpath://span[@class='ml-2'][normalize-space()='Cabang']"
add_cabang=  "xpath://button[@class='btn-active py-3 px-4 rounded-3xl flex items-center justify-center text-xs modal-button create-button']"
input_kode_cabang=  "xpath://div[@id='add-form-modal']//input[@placeholder='Ketik Kode Cabang']"
input_nama_cabang=  "xpath://div[@id='add-form-modal']//input[@placeholder='Ketik Nama Cabang']"
input_nama_pic=  "xpath://div[@id='add-form-modal']//input[@placeholder='Ketik Nama PIC']"
input_no_pic= "xpath://div[@id='add-form-modal']//input[@placeholder='Ketik Nomor WA PIC']"
input_lokasi_cabang=  "xpath://div[@id='add-form-modal']//input[@placeholder='Ketik Lokasi Cabang']"
input_edit_kode_cabang=  "xpath://div[@id='edit-form-modal']//input[@placeholder='Ketik Kode Cabang']"
input_edit_nama_cabang=  "xpath://div[@id='edit-form-modal']//input[@placeholder='Ketik Nama Cabang']"
input_edit_nama_pic=  "xpath://div[@id='edit-form-modal']//input[@placeholder='Ketik Nama PIC']"
input_edit_no_pic=  "xpath://div[@id='edit-form-modal']//input[@placeholder='Ketik Nomor WA PIC']"
input_edit_lokasi_cabang= "xpath://div[@id='edit-form-modal']//input[@placeholder='Ketik Lokasi Cabang']"
aksi=  "xpath://tbody/tr[1]/td[8]/div[1]/div[1]/div[1]//*[name()='svg']"
delete=  "xpath://button[@class='w-full delete-btn modal-button']"
Ya_hapus="xpath://button[normalize-space()='Ya, Hapus']"
