#Daftar Akun
button_daftar="id:btn-register"
button_submit_daftar="xpath://button[@type='submit'][normalize-space()='Daftar']"
input_nama_depan="xpath://input[contains(@placeholder,'Nama Depan')]"
input_nama_belakang="xpath://input[contains(@placeholder,'Nama Belakang')]"
input_no_hp="xpath://input[@placeholder='No. Hp']"
input_email="xpath://input[@placeholder='Email']"
input_password="xpath://input[@placeholder='Password']"
input_konfir_password="xpath://input[@placeholder='Konfirmasi Password']"
checkbox_agree="xpath://input[@name='isAgree']"
text_berhasil_daftar="xpath://h2[normalize-space()='Cek Email Anda']"
ya_mengerti_daftar="xpath://button[normalize-space()='Ya,Mengerti']"
